### ISSUE TITLE
Missing the weights

### ISSUE THREAD

**Issue by MartinKlefas** [google-deepmind/augmentations_medical_images#1]
I'm sorry if this has been answered elsewhere, but in your paper and the readme you mention that this repo would include the 'model weights for generative models trained on the public CAMELYON dataset' but the notebook just says to "download the open source models" I can't find them in the other repos linked to your papers - will you be able to publish them, or have their been regulatory issues in doing so?

**Comment by oawiles** [comment]
Hi -- they are linked within the [CoLAB](https://colab.research.google.com/github/google-deepmind/augmentations_medical_images/blob/master/camelyon17k_demo.ipynb#scrollTo=2HkRnXLvDEhG). If you open the CoLAB, you should see `We save our models using jax2tf for ease of use. Models can be downloaded with this link.` If you have any issues downloading the models, please let me know.

**Comment by MartinKlefas** [comment]
You're absolutely right, looks like I also need to find a better optometrist! Thank you for the swift response.
